Friends/Models/FriendModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Friends.Models
{
    public class FriendModel
    {
        [Required]
        [Range(0, 200)]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        [Display(Name = "Mesto na ziveenje")]
        public string MestoNaZiveenje { get; set; }

        public FriendModel(int id, string name, string mesto)
        {
            Id = id;
            Name = name;
            MestoNaZiveenje = mesto;
        }
        public FriendModel()
        {

        }
    }
}

Friends/Models/FriendsContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Friends.Models
{
    public class FriendsContext : DbContext
    {
        public DbSet<FriendModel> Friends { get; set; }
    }
}

Friends/Controllers/FriendApiController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Description;
using Friends.Models;

namespace Friends.Controllers
{
    public class FriendApiController : ApiController
    {
        private FriendsContext db = new FriendsContext();

        // GET: api/FriendApi
        public IQueryable<FriendModel> GetFriends()
        {
            return db.Friends;
        }

        // GET: api/FriendApi/5
        [ResponseType(typeof(FriendModel))]
        public async Task<IHttpActionResult> GetFriendModel(int id)
        {
            FriendModel friendModel = await db.Friends.FindAsync(id);
            if (friendModel == null)
            {
                return NotFound();
            }

            return Ok(friendModel);
        }

        // PUT: api/FriendApi/5
        [ResponseType(typeof(void))]
        public async Task<IHttpActionResult> PutFriendModel(int id, FriendModel friendModel)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != friendModel.Id)
            {
                return BadRequest();
            }

            db.Entry(friendModel).State = EntityState.Modified;

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!FriendModelExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/FriendApi
        [ResponseType(typeof(FriendModel))]
        public async Task<IHttpActionResult> PostFriendModel(FriendModel friendModel)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            db.Friends.Add(friendModel);
            await db.SaveChangesAsync();

            return CreatedAtRoute("DefaultApi", new { id = friendModel.Id }, friendModel);
        }

        // DELETE: api/FriendApi/5
        [ResponseType(typeof(FriendModel))]
        public async Task<IHttpActionResult> DeleteFriendModel(int id)
        {
            FriendModel friendModel = await db.Friends.FindAsync(id);
            if (friendModel == null)
            {
                return NotFound();
            }

            db.Friends.Remove(friendModel);
            await db.SaveChangesAsync();

            return Ok(friendModel);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool FriendModelExists(int id)
        {
            return db.Friends.Count(e => e.Id == id) > 0;
        }
    }
}

Friends/Controllers/FriendController.cs
using Friends.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Friends.Controllers
{
    public class FriendController : Controller
    {
        private FriendsContext friends = new FriendsContext();

        private static int friendToEdit;

        // GET: Friend
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ShowFriends(string searchString)
        {

            var model = friends.Friends
                        .Where(friend => String.IsNullOrEmpty(searchString) || friend.Name.Contains(searchString))
                        .OrderBy(friend => friend.Name);

            return View(model.ToList());
        }

        public ActionResult DeleteFriend(int id)
        {
            FriendModel m = friends.Friends.FirstOrDefault(f => f.Id == id);
            if(m != null)
                friends.Friends.Remove(m);
            friends.SaveChanges();
            return View("ShowFriends", friends.Friends.ToList());
        }

        public ActionResult EditFriend(int id)
        {
            FriendModel m = friends.Friends.FirstOrDefault(f => f.Id == id);
            friendToEdit = id;
            return View(m);
        }

        public ActionResult AddFriend()
        {
            FriendModel model = new FriendModel();
            return View(model);
        }
        [HttpPost]
        public ActionResult AddNewFriend(FriendModel model)
        {
            if (!ModelState.IsValid)
                return View("AddFriend");
            friends.Friends.Add(model);
            friends.SaveChanges();
            return View("ShowFriends", friends.Friends.ToList());
        }  

        [HttpPost]
        public ActionResult FriendEdited(FriendModel model)
        {
            FriendModel fr = friends.Friends.FirstOrDefault(f => f.Id == friendToEdit);
            if (!ModelState.IsValid) {
                return View("EditFriend", fr);
            }   
            friends.Friends.Remove(fr);
            friends.Friends.Add(model);
            friends.SaveChanges();
            return View("ShowFriends", friends.Friends.ToList());
        }

        protected override void Dispose(bool disposing)
        {
            if (friends != null)
                friends.Dispose();
            base.Dispose(disposing);
        }
    }
}

Friends/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Friends.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Friends/Views/Friend/AddFriend.cshtml
@model Friends.Models.FriendModel
@{
    ViewBag.Title = "AddFriend";
}

<h2>AddFriend</h2>

@{Html.BeginForm("AddNewFriend", "Friend");}
<p>
    @Html.LabelFor(m => m.Name)<br />
    @Html.TextBoxFor(m => m.Name)
    @Html.ValidationMessageFor(m => m.Name)
</p>

<p>
    @Html.LabelFor(m => m.Id)<br />
    @Html.TextBoxFor(m => m.Id, new { type = "number" })
    @Html.ValidationMessageFor(m => m.Id)
</p>

<p>
    @Html.LabelFor(m => m.MestoNaZiveenje)<br />
    @Html.TextBoxFor(m => m.MestoNaZiveenje)
    @Html.ValidationMessageFor(m => m.MestoNaZiveenje)
</p>

<input class = "btn btn-default" type="submit" value="Submit" />
    
@{ Html.EndForm();}
<br />
@Html.ActionLink("Back", "ShowFriends",null ,new { @class = "btn btn-default" })

Friends/Views/Friend/EditFriend.cshtml
@model Friends.Models.FriendModel
@{
    ViewBag.Title = "EditFriend";
}

<h2>EditFriend</h2>

@{ Html.BeginForm("FriendEdited", "Friend");}

@Html.LabelFor(m => m.Id) <br />
@Html.TextBoxFor(m => m.Id, Model.Id.ToString(), new {type = "number" })
@Html.ValidationMessageFor(m => m.Id)

<br />
<br />

@Html.LabelFor(m => m.Name) <br />
@Html.TextBoxFor(m => m.Name, Model.Name)
@Html.ValidationMessageFor(m => m.Name)

<br />
<br />

@Html.LabelFor(m => m.MestoNaZiveenje) <br />
@Html.TextBoxFor(m => m.MestoNaZiveenje, Model.MestoNaZiveenje)
@Html.ValidationMessageFor(m => m.MestoNaZiveenje)
<br />
<br />

<input class="btn btn-default" type="submit" value="Update" />
<br /><br />
@{ Html.EndForm();}
<a class="btn btn-default" href="~/Friend/ShowFriends">Back</a>

Friends/Views/Friend/ShowFriends.cshtml
@model List<Friends.Models.FriendModel>

@{
    ViewBag.Title = "ShowFriends";
}

<h2>ShowFriends</h2>

@*@using (Html.BeginForm("ShowFriends", "Friend", FormMethod.Get))
{
    @Html.TextBox("searchString")
    <input type="submit" name="Submit" class="btn btn-default"/>
}*@

<table id="friendsTable">
    <thead>
        <tr>
            <td>FriendID</td>
            <td>Friend Name</td>
            <td>Place</td>
            <td></td>
        </tr>
    </thead>
    <tbody>
        @{
        foreach (var friend in Model)
        {
            <tr>
                <td>@friend.Id</td>
                <td>@friend.Name</td>
                <td>@friend.MestoNaZiveenje</td>
                <td>
                    @Html.ActionLink("Edit", "EditFriend", new { id = friend.Id }, new { @class = "btn btn-default" })
                    <button class="btn btn-default js-delete" friend-id="@friend.Id">Delete</button>
                    @*@Html.ActionLink("Delete", "DeleteFriend", new { id = friend.Id }, new { @class = "btn btn-default" })*@
                </td>
            </tr>

    }
        }
    </tbody>
   
</table>

@section scripts {
    <script>
             $(document).ready(function () {
             var table = $("#friendsTable").DataTable();
             $("#friendsTable .js-delete").on("click", function () {
                var button = $(this);
                $.ajax({
                    url: "/api/FriendApi/" + button.attr("friend-id"),
                    method: "DELETE",
                    success: function () {
                        table.row(button.parents("tr")).remove().draw();
                    }
                });
            });
        });
    </script>
    }

Friends/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Friends/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Friends/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Friends/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Show Friends", "ShowFriends", "Friend")</li>
                    <li>@Html.ActionLink("Add Friend", "AddFriend", "Friend")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>